#! /bin/sh

# autostart
polybar &
picom --vsync &
sxhkd &
xwallpaper --zoom ~/Downloads/grey.jpg &
flatpak run net.waterfox.waterfox &
xbacklight -inc 100 &



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d web emacs term discord shit

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
